# Use the official Node.js image as a base
FROM node:16

# Set the working directory in the container
WORKDIR ./

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of your application code
COPY . .

# Expose the port the app runs on
EXPOSE 5000

# Command to run your application
CMD ["node", "index.js"]
