name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted  # Use self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 975050161532.dkr.ecr.us-east-2.amazonaws.com

      - name: Build Backend Docker image
        run: docker build -t backend-service ./backend

      - name: Build Frontend Docker image
        run: |
          # Create a .env file with the public IP for API URL
          echo "REACT_APP_API_URL=http://${{ secrets.EC2_PUBLIC_IP }}:5000" > ./frontend/.env
          docker build -t frontend-service ./frontend

      - name: Tag and Push Backend Docker image to ECR
        run: |
          docker tag backend-service:latest 975050161532.dkr.ecr.us-east-2.amazonaws.com/capstone-ecr:backend-latest
          docker push 975050161532.dkr.ecr.us-east-2.amazonaws.com/capstone-ecr:backend-latest

      - name: Tag and Push Frontend Docker image to ECR
        run: |
          docker tag frontend-service:latest 975050161532.dkr.ecr.us-east-2.amazonaws.com/capstone-ecr:frontend-latest
          docker push 975050161532.dkr.ecr.us-east-2.amazonaws.com/capstone-ecr:frontend-latest

      - name: Deploy to Docker
        run: |
          # Pull the latest images
          docker pull 975050161532.dkr.ecr.us-east-2.amazonaws.com/capstone-ecr:backend-latest
          docker pull 975050161532.dkr.ecr.us-east-2.amazonaws.com/capstone-ecr:frontend-latest
          
          # Stop and remove existing containers if they exist
          docker stop backend-service-container || true
          docker rm backend-service-container || true
          docker stop frontend-container || true
          docker rm frontend-container || true
          
          # Run new containers with port mapping
          docker run -d --restart always --name backend-service-container -p 5000:5000 975050161532.dkr.ecr.us-east-2.amazonaws.com/capstone-ecr:backend-latest
          docker run -d --restart always --name frontend-container -p 80:80 975050161532.dkr.ecr.us-east-2.amazonaws.com/capstone-ecr:frontend-latest
